title: U.S. 2020 Election API Resource Center
description: This is a toolbox of API collections, visualizations, and tooling to help make sense of the 2020 election in the United States. Providing a single landing page, documentation, and Postman collections that can be easily run using the Postman platform.
image: https://postman-toolboxes2.s3.amazonaws.com/assets/us-2020-election/postman-town-2020-election-350.png
url: https://postman-toolboxes2.github.io/us-2020-elections
email: covid-19@postman.com

github_user: postman-toolboxes2
github_repo: us-2020-elections
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'kin.lane@postman.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
